// Данные библиотеки - ЧИСТАЯ ВЕРСИЯ БЕЗ ДУБЛЕЙ
// Всего: 59 уникальных книг
const books = [
    // Исходные 3 книги
    {
        id: 1,
        title: 'Главный учебник HR в мире',
        author: 'Майкл Армстронг',
        publisher: 'Бомбора',
        year: 2020,
        isbn: '978-5-04-155820-8',
        genres: ['Бизнес', 'HR', 'Управление персоналом'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/9zVwz8xo',
        description: 'Фундаментальное руководство по управлению человеческими ресурсами, признанное во всем мире. Эта книга содержит проверенные практики и современные подходы к управлению персоналом в организациях любого масштаба.',
        series: null
    },
    {
        id: 2,
        title: 'Безграничный разум',
        author: 'Джо Боулер',
        publisher: 'Манн, Иванов и Фербер',
        year: 2020,
        isbn: null,
        genres: ['Психология', 'Саморазвитие', 'Образование'],
        genreKeys: ['psychology', 'education'],
        cover: 'https://www.genspark.ai/api/files/s/6fjlCKjl',
        description: 'Книга о том, как развить потенциал своего разума и преодолеть ограничивающие убеждения. Автор предлагает научно обоснованные методы развития когнитивных способностей и формирования установки на рост.',
        series: 'Библиотека Сбербанка, том 96'
    },
    {
        id: 3,
        title: 'Работа, которая заряжает',
        subtitle: 'Как не выгореть, занимаясь любимым делом',
        author: 'Елена Резанова',
        publisher: 'Манн, Иванов и Фербер',
        year: 2022,
        isbn: null,
        genres: ['Психология', 'Карьера', 'Саморазвитие'],
        genreKeys: ['psychology', 'career'],
        cover: 'https://www.genspark.ai/api/files/s/ITCpuFkL',
        description: 'Практическое руководство по профилактике профессионального выгорания. Автор делится эффективными техниками поддержания энергии и мотивации в работе, помогая найти баланс между продуктивностью и личным благополучием.',
        series: 'Измени свою жизнь'
    },
    {
        id: 4,
        title: 'Думай и предпринимай',
        author: 'Ольга Цаплина',
        publisher: 'Бомбора',
        year: 2024,
        isbn: null,
        genres: ['Бизнес', 'Предпринимательство'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/MBkAuxFv',
        description: 'Практическое руководство для предпринимателей о том, как думать и действовать эффективно в бизнесе.',
        series: null
    },
    {
        id: 5,
        title: 'Игры. Обучение. Тренинг. Досуг',
        author: 'Коллектив авторов',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Обучение', 'Тренинг', 'Психология'],
        genreKeys: ['education', 'psychology'],
        cover: 'https://www.genspark.ai/api/files/s/9kXK8OBZ',
        description: 'Сборник игр для интенсивного обучения, активного отдыха, коммуникативно-лингвистических и психотехнических игр. Включает игры для работы с текстом, деловые тренинги, игры-тесты и методики саморегуляции.',
        series: null
    },
    {
        id: 6,
        title: 'Отличная память в любом возрасте',
        subtitle: 'Как укрепить память и повысить умственные способности',
        author: 'Дэвид Перлмуттер, Кэрол Коулмэн',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Саморазвитие', 'Здоровье'],
        genreKeys: ['psychology'],
        cover: 'https://www.genspark.ai/api/files/s/w20ZwlxR',
        description: 'Научно обоснованные методы укрепления памяти и повышения умственных способностей в любом возрасте.',
        series: null
    },
    {
        id: 7,
        title: 'Фокусы мерчандайзинга',
        subtitle: 'Эффективные "трюки" для торговцев и поставщиков',
        author: 'Наталия Гузелевич',
        publisher: 'Питер',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Маркетинг', 'Продажи'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/bX2QIX2k',
        description: 'Практические приемы и стратегии мерчандайзинга для эффективной выкладки товаров и увеличения продаж.',
        series: null
    },
    {
        id: 8,
        title: 'Конкурентное сотрудничество в бизнесе',
        subtitle: 'Co-opetition',
        author: 'Адам Бранденбургер, Барри Нейлбафф',
        publisher: 'Кейс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Стратегия', 'Менеджмент'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/Tj0JmiwS',
        description: 'Революционный подход к бизнес-стратегии, объединяющий конкуренцию и сотрудничество для создания новых возможностей.',
        series: null
    },
    {
        id: 9,
        title: 'Никогда не ешьте в одиночку',
        subtitle: 'И другие правила нетворкинга',
        author: 'Кейт Феррацци, Тал Рэз',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Нетворкинг', 'Карьера'],
        genreKeys: ['business', 'career'],
        cover: 'https://www.genspark.ai/api/files/s/bcEhlnK0',
        description: 'Практическое руководство по построению эффективных деловых связей и развитию профессиональной сети контактов.',
        series: null
    },
    {
        id: 10,
        title: 'Бюджетирование как инструмент управления',
        subtitle: 'Книга 1',
        author: 'Александр Карпов',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Финансы', 'Управление'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/i5l7jujM',
        description: 'Первая книга из серии "100% практического бюджетирования" - практическое руководство по внедрению бюджетирования в компании.',
        series: 'Серия книг "100% практического бюджетирования"'
    },
    {
        id: 11,
        title: 'Управляя изменениями',
        subtitle: 'Как эффективно управлять изменениями в обществе, бизнесе и личной жизни',
        author: 'Ицхак Кальдерон Адизес',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент', 'Изменения'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/qrS6bJbN',
        description: 'Методология Адизеса по управлению организационными изменениями и трансформацией компаний.',
        series: 'Методология Адизеса'
    },
    {
        id: 12,
        title: 'Ведение бизнеса: Ключевые понятия',
        author: 'Джонатан Сазерленд, Дайан Кэнуэлл',
        publisher: 'Balance Business Books',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/b65SXfgQ',
        description: 'Справочник ключевых понятий и концепций ведения бизнеса для руководителей и предпринимателей.',
        series: null
    },
    {
        id: 13,
        title: 'Управление программами проектов на основе стандарта PMI',
        subtitle: 'Изложение методологии и рекомендации по применению',
        author: 'А. Н. Павлов',
        publisher: 'Бином',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Проектное управление', 'PMI'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/jQlPrW3K',
        description: 'Профессиональное руководство по управлению программами и проектами на основе стандарта PMI.',
        series: 'Проекты Программы Портфели'
    },
    {
        id: 14,
        title: 'Искусство вовлечения',
        subtitle: 'Как максимально полно раскрыть потенциал своих сотрудников',
        author: 'Джим Хоуден',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Менеджмент'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/HMqGnTHf',
        description: 'Проверенные методы успешного вовлечения сотрудников на каждом уровне организации.',
        series: 'Менеджмент — твоя работа'
    },
    {
        id: 15,
        title: 'Мастерство учителя',
        subtitle: 'Проверенные методики выдающихся преподавателей',
        author: 'Дуг Лемов',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Образование', 'Обучение', 'Методика'],
        genreKeys: ['education'],
        cover: 'https://www.genspark.ai/api/files/s/YOD5XNRz',
        description: 'Сборник эффективных методик преподавания от лучших учителей со всего мира.',
        series: null
    },
    {
        id: 16,
        title: 'Шесть дисциплин прорывного обучения',
        subtitle: 'Как превратить обучение и развитие в бизнес-результаты',
        author: 'Рой В. Х. Поллок, Эндрю МакК. Джефферсон, Кэлхун У. Уик',
        publisher: 'Сбербанк Корпоративный университет',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Обучение', 'HR'],
        genreKeys: ['business', 'education'],
        cover: 'https://www.genspark.ai/api/files/s/ffZ2wmvK',
        description: 'Методология превращения корпоративного обучения в измеримые бизнес-результаты.',
        series: null
    },
    {
        id: 17,
        title: 'Новые лидеры российского бизнеса',
        author: 'М. Кетс де Врис, С. Шекшня, К. Коротов, Э. Флорент-Трейси',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Лидерство', 'Менеджмент'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/30l4hJcm',
        description: 'Истории и опыт современных российских бизнес-лидеров, их подходы к управлению и развитию компаний.',
        series: null
    },
    {
        id: 18,
        title: 'Не в знании сила',
        subtitle: 'Как сомнения помогают нам развиваться',
        author: 'Стивен Д\'Соуза, Дайана Реннер',
        publisher: 'Альпина Паблишер',
        year: null,
        isbn: null,
        genres: ['Психология', 'Саморазвитие', 'Бизнес'],
        genreKeys: ['psychology', 'business'],
        cover: 'https://www.genspark.ai/api/files/s/Dcs0xKV2',
        description: 'Книга о том, как признание своего незнания и сомнения могут стать ключом к инновациям и личному росту.',
        series: null
    },
    {
        id: 19,
        title: 'Менталист. Чтение мыслей',
        subtitle: 'Примеры и упражнения',
        author: 'Торстен Хавенер',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Коммуникация'],
        genreKeys: ['psychology'],
        cover: 'https://www.genspark.ai/api/files/s/xku0YjmX',
        description: 'Практические упражнения по развитию навыков наблюдения, интуиции и понимания невербальных сигналов.',
        series: null
    },
    {
        id: 20,
        title: 'Организационная культура и эффективность бизнеса',
        author: 'Е.Д. Малинин',
        publisher: 'Московский психолого-социальный институт',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Организационная культура', 'Менеджмент'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/DVZgUQvf',
        description: 'Исследование влияния организационной культуры на эффективность бизнеса и методы ее формирования.',
        series: null
    },
    {
        id: 21,
        title: 'Кратко о психике',
        subtitle: 'Учебное пособие (Для широкого круга читателей)',
        author: 'Е. А. Климов',
        publisher: 'Московский психолого-социальный институт',
        year: null,
        isbn: null,
        genres: ['Психология', 'Образование'],
        genreKeys: ['psychology', 'education'],
        cover: 'https://www.genspark.ai/api/files/s/qLwGo3kd',
        description: 'Доступное введение в основы психологии и понимание психических процессов.',
        series: null
    },
    {
        id: 22,
        title: 'Кибербезопасность: правила игры',
        subtitle: 'Как руководители и сотрудники влияют на культуру безопасности в компании',
        author: 'Эллисон Сэрра',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Кибербезопасность', 'IT'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/rvkIBbNO',
        description: 'Практическое руководство по формированию культуры кибербезопасности в организации.',
        series: null
    },
    {
        id: 23,
        title: 'Прототипирование',
        subtitle: 'Практическое руководство',
        author: 'Тодд Заки Варфел',
        publisher: 'Rosenfeld',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Дизайн', 'UX'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/pCmWKjJj',
        description: 'Рекомендовано РБК. Практическое руководство по созданию прототипов продуктов и сервисов.',
        series: null
    },
    {
        id: 24,
        title: 'Цифровая трансформация Китая',
        author: 'Ма Хуатэн, Мэнь Чжаоли, Ян Дели, Ван Хуалей',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Технологии', 'Экономика'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/7INFEjeO',
        description: 'Анализ цифровой трансформации экономики Китая и уроки для мирового бизнеса.',
        series: null
    },
    {
        id: 25,
        title: 'Assessment Center для руководителей',
        subtitle: 'Опыт реализации в российской компании, упражнения, кейсы',
        author: 'М. В. Красностанова, Н. В. Осетрова, Н. В. Самара',
        publisher: 'Вершина',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Оценка персонала'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/4INDGRWz',
        description: 'Практический опыт внедрения и проведения центров оценки для руководителей в российских компаниях.',
        series: null
    },
    {
        id: 26,
        title: 'Как составить наилучший бизнес-план',
        subtitle: 'Для любой отрасли и сферы деятельности',
        author: 'Ронда Абрамс',
        publisher: 'Современные Бизнес-Технологии',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Планирование', 'Предпринимательство'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/NlrP9Wwl',
        description: 'Forbes и Стэнфордская школа бизнеса рекомендуют. Пятое международное издание практического руководства по составлению бизнес-планов.',
        series: null
    },
    {
        id: 27,
        title: 'Стратегическая карта, системный подход и KPI',
        subtitle: 'Инструменты для руководителей',
        author: 'Елена Ветлужских',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Стратегия', 'Менеджмент'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/TctR2RZo',
        description: 'Практические инструменты для разработки стратегии и системы KPI в организации.',
        series: null
    },
    {
        id: 28,
        title: 'Убеждай и побеждай',
        subtitle: 'Секреты эффективной аргументации',
        author: 'Никита Непряхин',
        publisher: 'Альпина Паблишер',
        year: null,
        isbn: null,
        genres: ['Психология', 'Коммуникация', 'Бизнес'],
        genreKeys: ['psychology', 'business'],
        cover: 'https://www.genspark.ai/api/files/s/czjE6guN',
        description: 'Практическое руководство по искусству аргументации и убеждения с предисловием Радислава Гандапаса.',
        series: null
    },
    {
        id: 29,
        title: 'Коучинг. Повышайте собственную эффективность',
        author: 'Макс Ландсберг',
        publisher: 'Эксмо',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Коучинг', 'Саморазвитие'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/coheWvKr',
        description: 'Международный бестселлер по коучингу. Практические методы повышения эффективности в работе и жизни.',
        series: 'Дао успешного бизнесмена'
    },
    {
        id: 30,
        title: 'Осторожно - острый ум!',
        subtitle: 'Золотые россыпи афоризмов',
        author: 'Сергей Сидоров, Веселин Георгиев',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Юмор', 'Афоризмы'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/YGASG2Em',
        description: 'Сборник задоринок и смехариков - остроумных афоризмов и цитат.',
        series: null
    },
    {
        id: 31,
        title: 'Финансы, денежное обращение и кредит',
        author: 'В.А. Галанов',
        publisher: 'Форум',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Финансы', 'Экономика'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/B3fsW7eX',
        description: 'Учебное пособие для профессионального образования в области финансов и банковского дела.',
        series: 'Профессиональное образование'
    },
    {
        id: 32,
        title: 'Взлом креатива',
        subtitle: 'Как увидеть то, что не видят другие',
        author: 'Майкл Микалко',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Креативность', 'Саморазвитие'],
        genreKeys: ['psychology'],
        cover: 'https://www.genspark.ai/api/files/s/Jl9HbDmw',
        description: 'Методы развития креативного мышления и способности видеть нестандартные решения.',
        series: null
    },
    {
        id: 33,
        title: 'У каждого свой Эверест',
        subtitle: 'Как опыт реальных восхождений помогает вдохновлять команды и управлять проектами',
        author: 'Сергей Кофанов',
        publisher: 'Бомбора',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент', 'Лидерство'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/AlGc3WwB',
        description: 'Уроки альпинизма и реальных восхождений применительно к управлению командами и проектами.',
        series: null
    },
    {
        id: 34,
        title: 'Думай как дизайнер',
        subtitle: 'Дизайн-мышление для менеджеров',
        author: 'Жанна Лиатка, Тим Огилви',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Дизайн-мышление', 'Инновации'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/WXb4hM11',
        description: 'Практическое руководство по применению дизайн-мышления в управлении и бизнесе.',
        series: null
    },
    {
        id: 35,
        title: 'Спиральная динамика',
        subtitle: 'Управляя ценностями, лидерством и изменениями в XXI веке',
        author: 'Дон Бек, Крис Кован',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Психология', 'Менеджмент'],
        genreKeys: ['business', 'psychology'],
        cover: 'https://www.genspark.ai/api/files/s/qoqhwZYJ',
        description: 'Теория спиральной динамики применительно к управлению организациями и социальными изменениями.',
        series: 'Серия Advanced Management Institute'
    },
    {
        id: 36,
        title: 'Формула времени',
        subtitle: 'Тайм-менеджмент на Outlook 2007',
        author: 'Глеб Архангельский',
        publisher: 'Microsoft',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Тайм-менеджмент', 'Продуктивность'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/qdLovBDd',
        description: 'Практическое руководство по тайм-менеджменту с использованием Microsoft Outlook 2007 от российского эксперта в области управления временем.',
        series: null
    },
    {
        id: 37,
        title: 'Техники подбора персонала',
        subtitle: 'Искусство находить лучших',
        author: 'Е. Н. Дубиненкова',
        publisher: 'Речь',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Рекрутинг'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/4s4jjyU9',
        description: 'Психологический тренинг по эффективным техникам подбора персонала. Как сделать подбор персонала максимально эффективным?',
        series: 'Психологический тренинг'
    },
    {
        id: 38,
        title: 'Озадачник',
        subtitle: '133 вопроса на знание логики, математики и физики',
        author: 'Павел Полуэктов, Николай Полуэктов',
        publisher: 'Альпина Паблишер',
        year: null,
        isbn: null,
        genres: ['Образование', 'Логика', 'Математика'],
        genreKeys: ['education'],
        cover: 'https://www.genspark.ai/api/files/s/wmQH72Lb',
        description: 'Editor\'s Choice. Сборник интересных задач и вопросов для развития логического мышления, математических и физических знаний.',
        series: null
    },
    {
        id: 39,
        title: 'Оценка качества менеджмента компаний',
        subtitle: 'Учебное пособие',
        author: 'Л. И. Шокина',
        publisher: 'КНОРУС',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент', 'Оценка'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/X0UgDR7H',
        description: 'Учебное пособие Финансовой академии при Правительстве РФ по методам оценки качества управления компаниями.',
        series: null
    },
    {
        id: 40,
        title: 'Современная практика корпоративного управления в российских компаниях',
        subtitle: 'Руководство для директора',
        author: 'Ассоциация независимых директоров',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Корпоративное управление', 'Менеджмент'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/OfSOkTVN',
        description: 'Опыт, приносящий успех. Практическое руководство по современному корпоративному управлению в российских компаниях.',
        series: 'Опыт, приносящий успех'
    },
    {
        id: 41,
        title: 'Говорить "нет" не испытывая чувства вины',
        author: 'Виктор Шейнов',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Коммуникация', 'Саморазвитие'],
        genreKeys: ['psychology'],
        cover: 'https://www.genspark.ai/api/files/s/JVhzUc7P',
        description: 'Практические техники и стратегии для уверенного отказа без чувства вины. Как научиться говорить "нет" и отстаивать свои границы.',
        series: null
    },
    {
        id: 42,
        title: 'Юридический минимум',
        subtitle: 'Главное, что нужно знать руководителю и бизнесмену',
        author: 'Алексей Мельников, Дмитрий Тихонов',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Право', 'Юриспруденция'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/s1zgopby',
        description: 'Необходимый минимум юридических знаний для руководителей и предпринимателей. Основы правовых аспектов ведения бизнеса.',
        series: null
    },
    {
        id: 43,
        title: 'Инструменты управления персоналом',
        subtitle: 'Аспекты кадрового документооборота',
        author: 'Коллектив авторов',
        publisher: 'Берег А',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Кадровое делопроизводство'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/cRjBHhZ2',
        description: 'Практическое руководство по кадровому документообороту и инструментам управления персоналом.',
        series: null
    },
    {
        id: 44,
        title: 'Как измерить HR-менеджмент',
        subtitle: 'Третье издание',
        author: 'Жак Фиц-Энц, Барбара Дэвисон',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Метрики'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/MzQrBlVe',
        description: 'Классическое руководство по измерению эффективности HR-функции. Методы и метрики для оценки работы службы персонала.',
        series: null
    },
    {
        id: 45,
        title: 'Классические работы по менеджменту',
        author: 'Питер Друкер',
        publisher: 'Сколково, Ведомости',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Менеджмент', 'Классика'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/bmV583kx',
        description: 'Сборник классических работ легендарного теоретика менеджмента Питера Друкера. Фундаментальные идеи об управлении организациями.',
        series: null
    },
    {
        id: 46,
        title: 'Сила в спокойствии',
        subtitle: 'Достижение гармонии с помощью трансцендентальной медитации',
        author: 'Боб Рот',
        publisher: 'Альпина Паблишер',
        year: null,
        isbn: null,
        genres: ['Психология', 'Медитация', 'Саморазвитие'],
        genreKeys: ['psychology'],
        cover: 'https://www.genspark.ai/api/files/s/n2FjNPd9',
        description: 'Бестселлер The New York Times. Практическое руководство по трансцендентальной медитации для достижения гармонии и снятия стресса.',
        series: null
    },
    {
        id: 47,
        title: 'От носорога к единорогу',
        subtitle: 'Как провести компанию через трансформацию в цифровую эпоху и избежать смертельных ловушек',
        author: 'Виктор Орловский, Владимир Коровкин',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Цифровая трансформация', 'Стартапы'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/UGMrO7Zj',
        description: 'Практическое руководство по трансформации традиционного бизнеса в успешную цифровую компанию-единорога.',
        series: null
    },
    {
        id: 48,
        title: 'Компания - создатель знания',
        subtitle: 'Зарождение и развитие инноваций в японских фирмах',
        author: 'И. Нонака, Х. Такеучи',
        publisher: 'Олимп-Бизнес',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Инновации', 'Менеджмент'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/4qDnV3tQ',
        description: 'Классическое исследование о том, как японские компании создают и используют знания для инноваций.',
        series: null
    },
    {
        id: 49,
        title: 'Развитие потенциала сотрудников',
        subtitle: 'Профессиональные компетенции. Лидерство, коммуникации',
        author: 'Светлана Иванова, Дмитрий Болдогеев, Эмма Борчанинова, Анна Глотова, Оксана Жигилий',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'HR', 'Управление персоналом'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/oNsAhfMS',
        description: 'От автора бестселлеров "Искусство подбора персонала" и "Мотивация на 100%". Развитие профессиональных компетенций сотрудников.',
        series: null
    },
    {
        id: 50,
        title: 'Психологический тренинг в группе',
        author: null,
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Обучение', 'Тренинги'],
        genreKeys: ['psychology', 'education'],
        cover: 'https://www.genspark.ai/api/files/s/wq0G9f99',
        description: 'Учебное пособие по проведению психологических тренингов в группах.',
        series: null
    },
    {
        id: 51,
        title: 'Договориться можно обо всём!',
        subtitle: 'Как добиваться максимума в любых переговорах',
        author: 'Гэвин Кеннеди',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Переговоры', 'Коммуникации'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/eMPrXjik',
        description: 'Практическое руководство по эффективным переговорам и достижению максимальных результатов в любых ситуациях.',
        series: null
    },
    {
        id: 52,
        title: 'Эффективный воркшоп',
        subtitle: 'Все о психологической группе',
        author: 'К. Фопель',
        publisher: 'Генезис',
        year: null,
        isbn: null,
        genres: ['Психология', 'Обучение', 'Тренинги'],
        genreKeys: ['psychology', 'education'],
        cover: 'https://www.genspark.ai/api/files/s/nI0dpUf0',
        description: 'Комплексное руководство по организации и проведению эффективных психологических воркшопов и групповой работы.',
        series: null
    },
    {
        id: 53,
        title: 'Дело не в кофе',
        subtitle: 'Корпоративная культура Starbucks',
        author: 'Говард Бехар',
        publisher: 'Альпина Бизнес Букс',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Корпоративная культура', 'Менеджмент'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/Aj6aegj0',
        description: 'Инсайдерский взгляд на корпоративную культуру Starbucks от бывшего президента компании. С предисловием Говарда Шульца.',
        series: 'The Moscow Times recommends'
    },
    {
        id: 54,
        title: 'Большая книга лучших игр и упражнений',
        subtitle: 'для любого тренинга',
        author: 'Михаил Кипнис',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Обучение', 'Тренинги'],
        genreKeys: ['psychology', 'education'],
        cover: 'https://www.genspark.ai/api/files/s/WPfhemOE',
        description: 'Коллекция лучших игр и упражнений для проведения любых тренингов.',
        series: 'Психология. Высший курс'
    },
    {
        id: 55,
        title: 'Занимательная психология',
        author: null,
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология'],
        genreKeys: ['psychology'],
        cover: 'https://www.genspark.ai/api/files/s/GH3LhfhF',
        description: 'Увлекательное введение в мир психологии через интересные факты и эксперименты.',
        series: 'Х файлы'
    },
    {
        id: 56,
        title: 'Корпоративные игры',
        subtitle: 'Пособие по выживанию',
        author: 'Джерри Гриффин, Сайран Паркер',
        publisher: 'Вершина',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Карьера', 'Корпоративная культура'],
        genreKeys: ['business', 'career'],
        cover: 'https://www.genspark.ai/api/files/s/xFvc8FiN',
        description: 'Практическое руководство по навигации в корпоративной среде и выживанию в офисной политике.',
        series: null
    },
    {
        id: 57,
        title: '5S для офиса',
        subtitle: 'Как организовать эффективное рабочее место',
        author: 'Том Фабрицио, Дон Тэппинг',
        publisher: 'Институт комплексных стратегических исследований',
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Продуктивность', 'Организация'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/VtsiB8JU',
        description: 'Применение японской системы 5S для организации эффективного рабочего пространства в офисе.',
        series: null
    },
    {
        id: 58,
        title: 'Тренинги - это классно',
        subtitle: 'Стратегия проведения психологических тренингов',
        author: 'Игорь Вагин, Павла Рипинская',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Психология', 'Обучение', 'Тренинги'],
        genreKeys: ['psychology', 'education'],
        cover: 'https://www.genspark.ai/api/files/s/LiFGhuLQ',
        description: 'Каждый человек обладает поистине безграничным потенциалом, и главное для тренера — этот потенциал раскрыть!',
        series: null
    },
    {
        id: 59,
        title: 'Академия продаж',
        author: 'Игорь Вагин, Павла Рипинская',
        publisher: null,
        year: null,
        isbn: null,
        genres: ['Бизнес', 'Продажи', 'Коммуникации'],
        genreKeys: ['business'],
        cover: 'https://www.genspark.ai/api/files/s/K5WPKUmX',
        description: 'Эффективные продажи — это искусство, которому можно научиться. Масса конкретных рекомендаций по продажам в различных секторах рынка.',
        series: null
    }
];
